title: "STM32-Docs"
description: "An augmented collection of the documentation provided by STMicroelectronics."
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
google_analytics: G-TJRSWGLQDX
